# SPDX-License-Identifier: GPL-2.0-only
# Hang debug core lives in kernel/hang_debug.c for central scheduler/binder
# integration. This directory is reserved for future Oplus-specific extensions.
# No objects built here directly; kernel/Makefile handles CONFIG_OPLUS_HANG_DEBUG.
