# SPDX-License-Identifier: GPL-2.0-only

ccflags-y += -I$(srctree)/techpack/camera-oppo/include/uapi
ccflags-y += -I$(srctree)/techpack/camera-oppo/drivers/cam_utils
ccflags-y += -I$(srctree)/techpack/camera-oppo/drivers/cam_core
ccflags-y += -I$(srctree)/techpack/camera-oppo/drivers/cam_cpas/include
ccflags-y += -I$(srctree)/techpack/camera-oppo/drivers/cam_cpas

obj-$(CONFIG_SPECTRA_CAMERA) += cam_camsstop_hw.o
