name: Build Aurora Kernel

on:
  push:
    branches: [ bpf-5.10-backport-qcom ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          bc bison build-essential flex git \
          libssl-dev libelf-dev lld llvm \
          python3 python-is-python3 \
          zip unzip cpio rsync curl \
          gcc g++ \
          binutils-aarch64-linux-gnu

    - name: Clone Clang 20
      run: |
        git clone --depth=1 https://gitlab.com/provasishh/clang-20.git tc

    - name: Build & Package Kernel
      run: |
        echo "Cloning AnyKernel..."
        git clone --filter=blob:none --depth=1 https://github.com/yassshhhh15/AnyKernel3.git -b rivena-bitra-spartan anykernel

        DT=$(date +"%Y%m%d-%H%M")
        CONFIG=vendor/kona-perf_defconfig

        export ARCH=arm64
        export OUT_DIR=$(pwd)/out
        export CROSS_COMPILE=$(pwd)/tc/aarch64-linux-android-4.9/bin/aarch64-linux-android-
        export CLANG_TRIPLE=aarch64-linux-gnu-

        export PATH="$(pwd)/tc/clang/bin:$PATH"

        export CC=clang
        export HOSTCC=clang
        export HOSTCXX=clang++

        compile() {
          echo "Compiling kernel..."

          make O=${OUT_DIR} \
            ARCH=${ARCH} \
            LLVM_IAS=1 \
            CROSS_COMPILE=${CROSS_COMPILE} \
            CC=${CC} \
            HOSTCC=${HOSTCC} \
            HOSTCXX=${HOSTCXX} \
            NM=llvm-nm \
            OBJCOPY=llvm-objcopy \
            OBJDUMP=llvm-objdump \
            STRIP=llvm-strip \
            ${CONFIG}

          make O=${OUT_DIR} \
            ARCH=${ARCH} \
            LLVM_IAS=1 \
            CROSS_COMPILE=${CROSS_COMPILE} \
            CC=${CC} \
            HOSTCC=${HOSTCC} \
            HOSTCXX=${HOSTCXX} \
            NM=llvm-nm \
            OBJCOPY=llvm-objcopy \
            OBJDUMP=llvm-objdump \
            STRIP=llvm-strip \
            -j$(nproc)
        }

        package() {
          echo "Packaging kernel..."

          cp out/arch/arm64/boot/Image anykernel/
          cp out/arch/arm64/boot/dtbo.img anykernel/
          cp out/arch/arm64/boot/dtb anykernel/

          cd anykernel
          zip -r9 Aurora-OOS16-${DT}.zip *
        }

        compile
        package

    - name: Upload flashable zip
      uses: actions/upload-artifact@v4
      with:
        name: Aurora-OOS16
        path: anykernel/*.zip
